title:              Kiwi's Blog
email:              your-email@example.com
description:        Boat Sailing at Night
author:             nikko1024
baseurl:            ""
url:                "https://nikko1024.github.io"

# Social Profiles
github_username:    nikko1024
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
